experiment_setups:
  "1": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 5
    g_start_pos: 7
    methois: "tbdex"
    param_index: 2

  "2": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 5
    g_start_pos: 7
    methois: "tbdex"
    param_index: 3,

  "3": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 10
    g_start_pos: 7
    methois: "evaluate"
    param_index: 4
    policy_key: default

  "4": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 10
    g_start_pos: 7
    methois: "evaluate"
    param_index: 5
    policy_key: default

  "5": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 10
    g_start_pos: 7
    methois: "evaluate"
    param_index: 5
    policy_key: default
    addition_index: 2

  "6": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 10
    g_start_pos: 7
    methois: "evaluate"
    param_index: 6
    policy_key: "default_0"
    addition_index: 3
    
  "7": # 这是配置集ID "1"
    train_days: 180
    val_days: 30
    freq: 30
    epchos: 10
    g_start_pos: 7
    methois: "train"
    param_index: 6
    policy_key: "default_0"
    addition_index: 4
    

