experiment_setups:
  "1": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "train"
    param_index: 2
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60

  "2": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "3": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 4
    addition_index: 2
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "4": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 5
    addition_index: 3
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "5": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "train"
    param_index: 6
    addition_index: 3
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "6": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 7
    addition_index: 3
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "7": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 7
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "8": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 7
    addition_index: 5
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "9": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 8
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "10": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 9
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "11": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 9
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_2"

  "12": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "evaluate"
    param_index: 9
    addition_index: 6
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "13": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 10
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "14": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "evaluate"
    param_index: 11
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "16": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 12
    addition_index: 7
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "17": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "evaluate"
    param_index: 12
    addition_index: 8
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"



  "t1": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "train"
    param_index: 1
    addition_index: 1
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_0"

  "t2": # 这是配置集ID "1"
    train_days: 180
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 2
    addition_index: 2
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "t3": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 2
    addition_index: 2
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_1"

  "t4": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    addition_index: 3
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_2"

  "t5": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_2"

  "t6": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_4"
    policy: "SACPolicyWithDropout"

  "t7": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_5"
    policy: "SACPolicyWithDropout"

  "t8": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "tbdex"
    param_index: 3
    addition_index: 4
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    swindow: 60
    policy_key: "default_6"
    policy: "SACPolicyWithDropout"






