experiment_setups:
  "1": # 这是配置集ID "1"
    train_days: 60
    val_days: 10
    freq: 10
    epchos: 10
    g_start_pos: 24
    methois: "train"
    param_index: 3
    addition_index: 5
    method: "aicso4"
    categories: "o2o"
    horizon: 1
    nc: 2
    feature_id: 2
    swindow: 60
    policy_key: "default_6"
    policy: "SACPolicyWithDropout"