"""统一目标到模拟撮合器或真实交易端的执行边界。"""

from strategy.execution.contracts import (
    AccountPositionSnapshot,
    ExecutionBackendKind,
    ExecutionReport,
    ExecutionReportType,
    OrderIntent,
    OrderSide,
    OrderType,
    PositionEffect,
)
from strategy.execution.nautilus import NautilusExecutionAdapter
from strategy.execution.order_state import (
    OrderLifecycleStatus,
    OrderReportStateMachine,
    OrderReportUpdate,
    OrderState,
    OrderStateCheckpoint,
    OrderStateError,
)
from strategy.execution.risk import (
    KillSwitchMode,
    MarketReferencePriceStore,
    PreTradeRiskManager,
    ReferencePrice,
    RiskDecision,
    RiskLimits,
    RiskRejected,
    RiskViolation,
    RiskViolationCode,
)
from strategy.execution.planner import NetTargetOrderPlanner
from strategy.execution.live import (
    BackendExecutionClient,
    NautilusLiveDriverPort,
    NautilusLiveExecutionBackend,
    NautilusTradingNodeDriver,
)
from strategy.execution.ctp import (
    CtpCloseAllocation,
    CtpClosePlanner,
    CtpCommissionRule,
    CtpExecutionAccounting,
    CtpFillResult,
    CtpLedgerState,
    CtpFuturesHedgingProfile,
    CtpPositionLedger,
    CtpPositionSnapshot,
    CtpSettlementResult,
)
from strategy.execution.ports import (
    ExecutionBackendPort,
    LiveExecutionBackendPort,
    OrderPlannerPort,
    SimExecutionBackendPort,
    VenueSimulationProfilePort,
)
from strategy.execution.simulation import (
    BinanceUsdtFuturesProfile,
    CtpFuturesBasicProfile,
    GenericVenueProfile,
    NautilusSimExecutionBackend,
    SimulationExecutionClient,
)

__all__ = [
    "AccountPositionSnapshot",
    "ExecutionBackendKind",
    "ExecutionBackendPort",
    "ExecutionReport",
    "ExecutionReportType",
    "BinanceUsdtFuturesProfile",
    "CtpFuturesBasicProfile",
    "CtpCloseAllocation",
    "CtpClosePlanner",
    "CtpCommissionRule",
    "CtpExecutionAccounting",
    "CtpFillResult",
    "CtpLedgerState",
    "CtpFuturesHedgingProfile",
    "CtpPositionLedger",
    "CtpPositionSnapshot",
    "CtpSettlementResult",
    "GenericVenueProfile",
    "BackendExecutionClient",
    "LiveExecutionBackendPort",
    "KillSwitchMode",
    "MarketReferencePriceStore",
    "NautilusExecutionAdapter",
    "NautilusLiveDriverPort",
    "NautilusLiveExecutionBackend",
    "NautilusTradingNodeDriver",
    "NautilusSimExecutionBackend",
    "SimulationExecutionClient",
    "OrderIntent",
    "OrderLifecycleStatus",
    "OrderReportStateMachine",
    "OrderReportUpdate",
    "OrderState",
    "OrderStateCheckpoint",
    "OrderStateError",
    "NetTargetOrderPlanner",
    "OrderPlannerPort",
    "OrderSide",
    "OrderType",
    "PositionEffect",
    "PreTradeRiskManager",
    "ReferencePrice",
    "RiskDecision",
    "RiskLimits",
    "RiskRejected",
    "RiskViolation",
    "RiskViolationCode",
    "SimExecutionBackendPort",
    "VenueSimulationProfilePort",
]
